Wdp210301 18
odevpl/wdp-2103-01 pull request #14
Opened 2021-03-18 17:53 UTC by pawisniewski

2021-03-19 08:12 UTC, odevpl commented on src/components/layout/Footer/Footer.js
> +          {/*
Jeśli ten fragment jest niepotrzebny, usuń go proszę

2021-03-19 08:12 UTC, odevpl requested changes
Niepotrzebne komentarze. Do kosza :)

2021-03-19 10:52 UTC, pawisniewski commented on src/components/layout/Footer/Footer.js
> +          {/*
Komentarz został usunięty :)

2021-03-19 10:53 UTC, pawisniewski commented
Komentarz został usunięty :)

2021-03-21 09:42 UTC, odevpl approved these changes

2021-03-21 09:42 UTC, merged