Add Rating component
odevpl/wdp-2103-01 pull request #31
Opened 2021-03-22 19:43 UTC by pawisniewski

2021-03-25 15:03 UTC, pawisniewski commented
Konflikty rozwiązane :)

2021-03-26 00:35 UTC, szygadlinski reviewed
Hej, dwa miejsca w kodzie Ci skomentowałem :)

2021-03-26 00:35 UTC, szygadlinski commented on src/components/common/Rating/Rating.js
> +            )}
Hej! :D Wydaje mi się że można usunąć linie 27-36 oraz 18, a warunek dać w `icon={star > rate ? farStar : faStar}` ? :)

2021-03-26 00:35 UTC, szygadlinski commented on src/components/common/Rating/Rating.module.scss
> +  }
I chyba zwykłe gwiazdki przed oceną na hover też powinny być pomarańczowe jeśli dobrze rozumiem polecenie :(

2021-03-26 09:49 UTC, pawisniewski commented on src/components/common/Rating/Rating.js
> +            )}
Good point :)
Tak też zrobiłem.

2021-03-26 09:50 UTC, doforever reviewed
Poza kolorem onHover spełnia założenia. Dispatchujesz starsznie dużo eventów ;-)

2021-03-26 09:50 UTC, doforever commented on src/components/common/ProductBox/ProductBox.js
> +  number,
Może się czepiam, ale nazwa tego propsa niewiele mówi

2021-03-26 09:50 UTC, doforever commented on src/components/common/ProductBox/ProductBox.js
> +          rated={rated}
Przekazujesz bardzo dużo propsów, które możnaby pobierać ze stora. Ja bym chyba poszła w napisanie kontenera komponentu Rating, żeby łatwiej się go uruchamiało.

2021-03-26 09:50 UTC, doforever commented on src/components/common/Rating/Rating.module.scss
> +  }
Popieram

2021-03-26 09:50 UTC, doforever commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Do czego  potrzebne Ci są eventy toggleColor i hoverStar. Ja widzę zmianę w storze tylko po odpaleniu toggleStar.

2021-03-26 09:51 UTC, pawisniewski commented on src/components/common/Rating/Rating.module.scss
> +  }
Jeśli chodzi o kolor to zrobiłem tak celowo, żeby wyeksponować jakoś moment kliknięcia.

2021-03-26 09:54 UTC, pawisniewski commented on src/components/common/ProductBox/ProductBox.js
> +  number,
Number nie jest mój, pojawił się w momencie rebase do mastera.

2021-03-26 09:56 UTC, pawisniewski commented on src/components/common/ProductBox/ProductBox.js
> +          rated={rated}
Myślałem nad tym na początku, jednak nie wziąłem pod uwagę, że Rating będzie używany jeszcze gdzieś poza ProductBoxem.

2021-03-26 09:59 UTC, pawisniewski commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Jeśli chodzi o kolor to zrobiłem tak celowo, żeby wyeksponować jakoś moment kliknięcia.

2021-03-26 10:05 UTC, doforever commented on src/components/common/ProductBox/ProductBox.js
> +  number,
To chyba już dawno nie używany. Już usuwałam go kilka razy

2021-03-26 10:06 UTC, doforever commented on src/components/common/ProductBox/ProductBox.js
> +          rated={rated}
Będzie, w GalleryProduct i Promoted też są wyrenderowane widoki produktów z gwiazdkami

2021-03-26 10:07 UTC, doforever commented on src/components/common/ProductBox/ProductBox.js
> +          rated={rated}
No chyba, że napiszemy w końcu generyczny komponent produktu, który proponowałam.

2021-03-26 10:08 UTC, doforever commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
A w jakim celu dispatchujesz te eventy?

2021-03-26 11:11 UTC, pawisniewski commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Bo nie wpadłem na inny sposób jak by zrobić na gwiazdkach efekt Hover oraz zmianę Color. Myślałem nad CSS ale zrezygnowałem.

2021-03-26 11:27 UTC, doforever commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Wydaje mi się, że css jest bardziej logicznym wyborem, albo jakaś lokalna funkcja handle hover. Dispatchowanie akcji chyba nie jest tu potrzebne.

2021-03-26 17:53 UTC, szygadlinski approved these changes

2021-03-26 19:51 UTC, pawisniewski commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Zmianę Color rozwiązałem inaczej bez większych przeszkód. Na inna mechanikę Hovera nie mam niestety pomysłu.

2021-03-26 22:18 UTC, doforever commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Wystarczy ci stan komponentu, w którym zapisujesz myRating i odpalasz jego zmianę na onMouseEnter:
```js
const Rating = ({ id, rate, toggleStar, rated }) => {
  const [myRate, setMyRate] = useState(rate);

  const handleHover = i => {
    setMyRate(i+1);
  };

  return (
    <div className={!rated ? styles.stars : styles.starsRated}>
      {[1, 2, 3, 4, 5].map((star, i) => {
        const rateValue = i + 1;
        return (
          <a key={star} href='/#'>
            <label>
              <input type='radio' name='rating' value={rateValue} />
              <FontAwesomeIcon
                onClick={() => toggleStar({ id, rateValue })}
                onMouseEnter={() => handleHover(i)}
                icon={star > myRate ? farStar : faStar}
              />
            </label>
          </a>
        );
      })}
    </div>
  );
};

2021-03-26 22:19 UTC, doforever commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
U mnie działa ;-)

2021-03-26 22:21 UTC, doforever commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Jestem pewna, że to lepsza opcja. Co Ty na to?

2021-03-26 22:23 UTC, doforever requested changes
Wpisałam moją propozycję w rozmowie. Myślę, że najlepiej będzie zrezygnować z akcji HOVER_STAR

2021-03-27 12:16 UTC, pawisniewski commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Prawie działa. W tym momencie po ocenieniu produktu możemy dalej najeżdżać kursorem na Rating zmieniając jego stan a tego nie chcemy. Przydałby się gdzieś warunek, że handleHover działa tylko jeśli product.rated !== true. Masz pomysł?

2021-03-27 12:20 UTC, pawisniewski commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Albo np zresetowanie stanu komponentu onMouseLeave.

2021-03-27 12:42 UTC, pawisniewski commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Dobra. Ogarnąłem warunek. Teraz działa identycznie jak wcześniej :)

2021-03-27 14:20 UTC, doforever commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Chyba nie do końca. Ja nie zauważyłam tego problemu wcześniej. Jak kolejny raz klikasz na gwiazdkę, to ocena zmienia się w storze, ale nie zmienia się wyświetlana ilość pomarańczowych gwiazdek :-(

2021-03-27 15:24 UTC, pawisniewski commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Zablokowałem to. Teraz ponowne kliknięcie nic nie zmienia w stanie produktu. Jest to system jednorazowego głosowania :)

2021-03-27 20:34 UTC, doforever commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  hoverStar: value => dispatch(hoverStar(value)),
Zobaczymy, co powie na to "klient" ;-)

2021-03-27 20:36 UTC, doforever approved these changes
Trochę się z tym bujałeś, ale działa :-)

2021-03-28 10:17 UTC, merged