Add functionality for Feedback
odevpl/wdp-2103-01 pull request #32
Opened 2021-03-22 23:19 UTC by anna130993

2021-03-24 08:41 UTC, odevpl commented on src/App.js
> +          <Route exact path={'/product'} component={Products} />
Hej!
Podstrona produkt już istnieje :)

2021-03-24 08:42 UTC, odevpl requested changes
Podstrona produkt już istnieje. Nie ma sensu tworzyć duplikatu :)

2021-03-24 08:49 UTC, anna130993 commented
Już usunięte. :) Musiałam się zagapić pewnie. :)

2021-03-25 09:08 UTC, odevpl approved these changes

2021-03-25 09:08 UTC, odevpl commented on src/App.js
> +import Products from './components/views/Products/Products';
Do kosza

2021-03-25 09:08 UTC, odevpl commented on src/components/views/Products/Products.module.scss
> +@import "../../../styles/settings.scss";
Ten plik cały do kosza

2021-03-25 09:08 UTC, odevpl commented on src/components/views/Products/Products.js
> +import React from 'react';
Ten również do kosza

2021-03-25 09:16 UTC, anna130993 commented
Done. :)

2021-03-25 09:36 UTC, merged