WDP210301-32
odevpl/wdp-2103-01 pull request #33
Opened 2021-03-23 00:16 UTC by szygadlinski

> Zadaniem jest stworzenie wersji mobilnych sekcji "Brands". Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
> W sliderze ma być tyle elementów, ile zmieści się w całości na danej szerokości ekranu.
> Ma działać przesuwanie slajdów za pomocą komponentu Swipeable (jest na niego osobne zadanie – jeśli nie jest gotowe to trzeba przygotować funkcje, które będą wykonywane przy swipe w lewo i w prawo).

RWD i funkcje do swipe zrobione.

2021-03-24 08:44 UTC, odevpl commented on src/components/features/Brands/Brands.js
> +    if (window.innerWidth <= 511) {
Hej! Mamy już funkcjonanlość, która tworzy breakpointy na podstawie szerokości :)
Może by tak skorzystać z niej?

2021-03-24 08:44 UTC, odevpl requested changes
Uwagi przy kodzie :)

2021-03-27 21:23 UTC, doforever commented on src/components/features/Brands/Brands.js
> +    if (window.innerWidth <= 511) {
Ja bym strzelała, że chodzi o to, że na masterze MainLayout robi determineWindowWidth i zapisuje w storze deviceType mobile/tablet/desktop. Tylko, że na Twoim branchu tego nie robi...

2021-03-27 21:40 UTC, doforever requested changes
Zrób rebase, wszystko stanie się łatwiejsze.

2021-03-27 21:40 UTC, doforever commented on src/components/features/Brands/Brands.js
> +    if (window.innerWidth <= 511) {
No i jeszcze jedna sprawa. Twój kod działa tylko po wyrenderowaniu komponentu. Nic nie wymusza przeliczenia ilości kafelków po zmianie szerokości okna.

2021-03-28 15:43 UTC, szygadlinski commented on src/components/features/Brands/Brands.js
> +    if (window.innerWidth <= 511) {
Oki, to zajmę się tym jutro :)

2021-03-29 16:04 UTC, szygadlinski commented
Hej, zrobiłem rebase i jeśli chodzi o RWD to usunąłem to moje rzeźbienie ;) i w sumie to slider responsywny już jest, w związku z tym czy ja powinienem jeszcze coś z tym zrobić? 

Jeśli zaś chodzi o `Swipeable`, to skorzystałem z funkcji które były przygotowane do kliknięć i też działa, tylko zastanawia mnie dlaczego na `onClick` funkcja musi przyjmować `event`, a na `swipe` nie może go przyjmować, inaczej nie działa. Rozjaśnicie mi? :D

2021-03-29 19:23 UTC, doforever commented
> Hej, zrobiłem rebase i jeśli chodzi o RWD to usunąłem to moje rzeźbienie ;) i w sumie to slider responsywny już jest, w związku z tym czy ja powinienem jeszcze coś z tym zrobić?
> 
> Jeśli zaś chodzi o `Swipeable`, to skorzystałem z funkcji które były przygotowane do kliknięć i też działa, tylko zastanawia mnie dlaczego na `onClick` funkcja musi przyjmować `event`, a na `swipe` nie może go przyjmować, inaczej nie działa. Rozjaśnicie mi? :D

Dlatego, że do Swipeable przekazujesz definicję funkcji i w komponencie ona potem jest przypisywana do onTouch i onMouse cośtam i wtedy jest jej przekazywany event? A onClick potrzebuje mieć event żeby zrobić prevent default. Zgaduję ;-)

2021-03-29 19:33 UTC, doforever reviewed
Dla mnie kod wygląda bardzo elegancko. Chyba masz jeszcze coś odrobinę nie dopasowane z wielkościami marginesów w blokach if dla funkcji moveLeft i moveRight. Bo nie ustawia się dobrze na końcach przewijania, a po ponownym kliknięciu się poprawia.

2021-03-29 19:34 UTC, doforever approved these changes

2021-03-29 20:50 UTC, PatrykBula approved these changes

2021-03-29 20:50 UTC, merged