Add ColorFilter
odevpl/wdp-2103-01 pull request #47
Opened 2021-03-24 20:01 UTC by anna130993

2021-03-24 20:11 UTC, anna130993 commented
Zmiana w CategoryFilter.module.scss wynika z dostosowania głównego lewego marginu do obserwacji dokonanej w trakcie robienia ColorFilter - wiem, że to wszystko i tak się inaczej ułoży, jak będzie konkretna zawartość, ale teraz robiłam jeszcze bez i chciałam, żeby to wyglądało porządnie i jak najbardziej podobnie do wizualizacji, a poprzesuwało się w stosunku do wcześniejszej wersji. :)

2021-03-25 09:19 UTC, odevpl requested changes
Przeanalizuj proszę swój kod jeszcze raz

2021-03-25 09:19 UTC, odevpl commented on src/components/views/ProductList/ProductList.js
> +    <Banner />
usuń

2021-03-25 09:19 UTC, odevpl commented on src/components/views/ProductList/ProductList.js
> +    <CategoryFilter />
usuń

2021-03-25 09:19 UTC, odevpl commented on src/styles/settings.scss
> -//*******COLOURS - VARIABLES*******//
Czemu kasujesz ten plik?

2021-03-25 09:19 UTC, odevpl commented on src/redux/initialState.js
> -const initialState = {
Czemu kasujesz ten plik?

2021-03-25 19:25 UTC, closed without merging