WDP210301-26
odevpl/wdp-2103-01 pull request #52
Opened 2021-03-25 18:05 UTC by szygadlinski

> Zadaniem jest stworzenie wersji mobilnych sekcji "Promocje". Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
> Na szerokościach, gdzie trzy boxy nie mieszczą się obok siebie, należy ułożyć je jeden pod drugim (największy na górze, pod nim dwa mniejsze).

RWD dla Deals dodane.

2021-03-25 18:49 UTC, odevpl requested changes
Zerknij w komentarze.

2021-03-25 18:49 UTC, odevpl commented on src/components/features/NewFurniture/NewFurniture.js
> +                'row' + (isFading ? ' ' + styles.fadeout : ' ' + styles.fadein)
Potrafie lepiej!

2021-03-25 18:49 UTC, odevpl commented on src/components/features/NewFurniture/NewFurniture.js
> +                .slice(activePage * 8, (activePage + 1) * 8)
Zamień to!

2021-03-25 18:52 UTC, odevpl commented on src/components/features/NewFurniture/NewFurniture.js
> +                'row' + (isFading ? ' ' + styles.fadeout : ' ' + styles.fadein)
nie ...

2021-03-26 15:35 UTC, odevpl approved these changes

2021-03-26 22:31 UTC, doforever approved these changes
Bardzo ładnie wygląda i robi to co miało robić :-)

2021-03-27 01:18 UTC, merged