Add functionality for Feedback
odevpl/wdp-2103-01 pull request #54
Opened 2021-03-25 19:50 UTC by anna130993

W initialState.js od razu przekleiłam też brandsy 6-24 do, well, Brandsów - tym bardziej, że ja je kiedyś robiłam i nie wiem, czemu tak je rozwaliło, bo było okej. o.O

2021-03-28 10:26 UTC, odevpl requested changes
Czemu brandsy w feedbacku?

2021-03-28 10:26 UTC, odevpl commented on src/redux/initialState.js
> +  ],
Czemu dorzucasz brandsy w feedbacku?

2021-03-28 12:04 UTC, anna130993 commented on src/redux/initialState.js
> +  ],
Nie tyle dorzucam, co naprawiałam - dodawałam je wcześniej przy innym zadaniu w dobrym miejscu, a teraz zauważyłam, że były tak dziwnie wycięte i przerzucone gdzie indziej zupełnie, nie wiem, co tu się wydarzyło. o.O Stwierdziłam po prostu, że skoro widzę, to od razu naprawię; wydawało mi się,  że nie bardzo jest sens robić osobnego ticketa tylko na jedno 'wytnij i wklej'. :)

2021-03-28 12:35 UTC, anna130993 commented on src/redux/initialState.js
> +  ],
(A to, co zaczyna się pod brandem 24 jest już nie moje - było tak dziwnie doklejone tam, więc już zostawiłam przy tym, żeby nie niszczyć działania strony, ale nie mam pojęcia, pod jaką nazwą powinno być to zapisane, gdzie de facto powinno być ani nic w tym stylu - to już robota dla kogoś innego. 🤷‍♀️ )

2021-03-28 12:51 UTC, anna130993 commented on src/redux/initialState.js
> +  ],
Okej, już widzę, że był na to osobny ticket po drodze i ktoś się tym zajął w międzyczasie - już wycofuję się z brandsów w takim razie i ogarniam na podstawie tamtego. :)

2021-03-28 13:03 UTC, anna130993 commented
Już wyrównałam plik initialState.js do zmian, które poszły w międzyczasie z innego ticketa - przekopiowałam manualnie od razu w Pull Requeście aktualny plik z mastera na miejsce starego i dodałam tylko Feedback. :)

2021-03-29 20:02 UTC, doforever requested changes
Tyle moich uwag po przeczytaniu kodu. Niestety chyba coś poszło nie tak przy mergowaniu, bo mi się w ogóle ten branch nie kompiluje :-(

2021-03-29 20:56 UTC, anna130993 commented on src/components/features/Feedback/Feedback.js
> +            }}
Nie wiem, dlaczego nie kompiluje Ci się strona (  :(  ), ale Swipeable jak najbardziej działa dobrze z takim zapisem i bez leftAction/rightAction, czyli nie są one niezbędne - a za props opcjonalny dziękuję, ale nie używam myszki, więc i tak nie przetestuję. 😀

2021-03-29 21:48 UTC, anna130993 commented
Przerobiłam trochę Feedback.js, tak żeby zmniejszyć ilość kodu, wykorzystać propsy ze Swipeable i wcześniejsze sugestie  - z tego co widzę, u mnie wszystko działa bardzo ładnie, także nie mam też pojęcia, skąd wynikały wcześniejsze problemy - mam nadzieję, że już jest okej. 😀

2021-03-29 21:50 UTC, anna130993 commented on src/components/features/Feedback/Feedback.js
> +            }}
W ten sposób też działało, ale faktycznie, przerobiłam tak, żeby wykorzystać te propsy i żeby było jednolicie w projekcie, no i mniej kodu jednocześnie - wydaje mi się, że wyszło fajnie. :)

2021-03-29 21:51 UTC, anna130993 commented on src/components/features/Feedback/Feedback.js
> +                });
Nie było żadnego innego problemu, po prostu tak rozpisałam za pierwszym razem, a ponieważ wszystko ładnie działało, to nawet się nad tym nie zastanawiałam - ale teraz wykorzystałam tę sugestię przy przerobieniu kodu i wydaje mi się, że oszczędziło to sporo miejsca koniec końców. :)

2021-03-30 08:10 UTC, doforever commented on src/components/features/Feedback/Feedback.js
> +            }}
Wyszło fajnie :-)

2021-03-30 08:13 UTC, doforever reviewed
Zmiany wyszły fajnie. Kod jest bardziej zwięzły i czytelny. Nie wiem o co chodzi, ale nadal mi się nie kompiluje...

2021-03-30 17:08 UTC, anna130993 commented
Okej, więc tak - wcześniej umknęła mi sytuacja z toggleStar (nauczka na przyszłość - trzeba być ostrożniejszym), więc teraz posłałam się na misję naprawienia brancha tak, aby kompilował się bez konieczności robienia czegokolwiek więcej. Jak widać po force-pushach, wcześniej przekombinowałam i mój pierwotny plan backfired, więc pojawiły się dwa dodatkowe pliki, które nie mają nic wspólnego z samym zadaniem:
- zaktualizowany do obecnej wersji w masterze ProductBoxContainer - za którego pośrednictwem siłą rzeczy zmienił się ten wadliwy-pierwotny;
- zaktualizowany ProductList.test.js - husky nie chciał mnie przepuścić; na szczęście widziałam, że @doforever już rozwiązała odpowiedniego ticketa, więc pożyczyłam rozwiązanie. 😀 

Teraz wszystko powinno już otwierać się ładnie i bez żadnych przeszkód.
(Note to myself - zwracać większą uwagę na detale nie związane bezpośrednio z zadaniem). :)

2021-03-30 20:09 UTC, doforever approved these changes
Działa to co na masterze, nie działa też to co na masterze ;-) Good job!

2021-03-31 12:21 UTC, PatrykBula approved these changes

2021-03-31 12:23 UTC, merged