Add ColorFilter
odevpl/wdp-2103-01 pull request #57
Opened 2021-03-25 21:26 UTC by anna130993

Uwaga - na początku minusowy margin nad filtrem może razić, ale tak jak w przypadku CategoryFilter nabierze on sensu po tym, jak wcześniejsze tickety trafią do mastera - filtr powinien przylegać  ciasno do wcześniejszych filtrów, więc w zestawieniu z resztą ten zabieg działa (a przynajmniej działał przy jeszcze wcześniejszym sprawdzaniu). :)

2021-03-26 18:04 UTC, anna130993 commented
Konflikt rozwiązany - dopisałam też od razu CategoryFilter, ale tylko i wyłącznie po to, żeby - hopefully - uniknąć jutro kolejnego konfliktu, który niechybnie bym miała sama ze sobą, kiedy CategoryFilter trafi pierwszy do mastera - tak jak było z Category Filter i Bannerem dzisiaj. :)

2021-03-28 18:22 UTC, cptTimon requested changes

2021-03-28 18:22 UTC, cptTimon commented on src/components/features/ColorFilter/ColorFilter.module.scss
> +  margin-left: 1219px;
Ogólnie wszystko jest git, tylko skąd ten margin-left? To jakieś przeoczenie, czy ma ukryty sens, którego nie dostrzegam? :D

2021-03-28 18:22 UTC, cptTimon commented on src/components/features/ColorFilter/ColorFilter.module.scss
> +      margin-left: 30px;
Wydaje mi się, że na wizualizacji taska ten 'odskok' kolorów jest troszeczkę mniejszy - ale to tylko kwestia gustu, a piszę, żeby sobie poćwiczyć komentarze :D

2021-03-28 18:22 UTC, cptTimon commented on src/components/features/ColorFilter/ColorFilter.module.scss
> +  margin-left: 1219px;
W każdym razie chwilę mi zajęło w ogóle znalezienie tego filtra na stronie  ;d

2021-03-28 18:22 UTC, cptTimon commented on src/components/features/ColorFilter/ColorFilter.module.scss
> +  margin-left: 1219px;
Dlatego zaznaczam 'request changes' bo myślę, że tam powinno być 12 px

2021-03-28 19:29 UTC, anna130993 commented on src/components/features/ColorFilter/ColorFilter.module.scss
> +  margin-left: 1219px;
A widzisz, to miało bardzo duży sens przed restrukturyzacją strony - kiedy był na niej tylko baner, żeby zobaczyć filtr na desktopie i żeby układał się odpowiednio w stosunku do baneru, te marginesy były niezbędne; teraz faktycznie przeszkadzają, więc jak najbardziej usuwam - dzięki za tip! :)

2021-03-28 19:29 UTC, anna130993 commented on src/components/features/ColorFilter/ColorFilter.module.scss
> +      margin-left: 30px;
Haha, nie ma problemu, możesz ćwiczyć. 😀 W ramach kompromisu dam 20px, powinno być okej. 😂

2021-03-28 20:07 UTC, cptTimon approved these changes
Teraz jest wspaniale!! A jak się na tym czacie dodaje emotki?

2021-03-28 23:12 UTC, anna130993 commented
Awww, dzięki. 😁  Musisz zacząć od ":" i potem szukasz, której potrzebujesz słowami-kluczami po angielsku - generalnie one są tak samo zakodowane, jak na czacie Kodilli. 😁

2021-03-29 20:55 UTC, odevpl approved these changes

2021-03-29 20:55 UTC, merged