WDP210301-53
odevpl/wdp-2103-01 pull request #66
Opened 2021-03-29 21:53 UTC by szygadlinski

> Twoim zadaniem jest dodanie sekcji newsletter oraz brands do podstron product oraz shop.
> W niektórych miejscach może już występować.

Dodane, ale jako że nie mamy sekcji newsletter, założyłem że chodziło o `Feedback`? Jeśli nie to usunę :)
Usunąłem też kolejny raz starą tablicę `brands` z `initialState`, gdyż wciąż były dwie, a właściwa tylko jedna :)

2021-03-30 16:06 UTC, cptTimon approved these changes
Nie ma tu za bardzo co sprawdzać, ale wszystko wygląda ok 😄

2021-03-31 12:27 UTC, odevpl requested changes
2 uwagi. Popraw je proszę

2021-03-31 12:27 UTC, odevpl commented on src/components/views/ProductList/ProductList.js
> +import ProductBox from '../../common/ProductBox/ProductBoxContainer';
Do kosza

2021-03-31 12:27 UTC, odevpl commented on src/components/views/ProductPage/ProductPage.js
> +    <NewFurniture rowSize={4} />
Czemu container zniknął?

2021-03-31 12:32 UTC, szygadlinski commented
ProductBox nie był mój ale usunąłem, a kontener z tego co widzę to jest przecież? Może wrócił po rozwiązaniu konfliktu?

2021-04-01 20:08 UTC, odevpl approved these changes

2021-04-01 20:08 UTC, merged