WDP210301-29
odevpl/wdp-2103-01 pull request #69
Opened 2021-03-30 20:54 UTC by anna130993

Poza RWD dla Gallery, dodałam też drobne zmiany dla CategoryFilter.module.scss, których nie zdążyłam nanieść w odpowiednim zadaniu - wcześniej usunięte marginesy były niezbędne dla widoczności filtru, ale po restrukturyzacji ProductList i przeniesieniu filtrów do div-3 zaczęły przeszkadzać, zamiast pomagać. :)

2021-03-30 23:57 UTC, szygadlinski requested changes
Hej, dwa drobiazgi trzeba by było chyba zmienić :D

2021-03-30 23:57 UTC, szygadlinski commented on src/components/features/Gallery/Gallery.js
> +    <Swipeable leftAction={handleSliderBackward} rightAction={handleSliderForward}>
Hej hej! Wykrzacza się przy swipe'owaniu :P a to dlatego, że musiałabyś do `leftAction` i `rightAction` przekazać tą samą fukcję którą przekazałaś, ale bez eventu w argumencie i bez `event.preventDefault()` :)

2021-03-30 23:57 UTC, szygadlinski commented on src/components/features/Gallery/Gallery.module.scss
> +}
I jeszcze na szerokościach tabletowych to zdjęcie z prawej wyświetla się pod tym elementem ze sliderem, a nie obok :(

2021-03-31 00:12 UTC, anna130993 commented on src/components/features/Gallery/Gallery.js
> +    <Swipeable leftAction={handleSliderBackward} rightAction={handleSliderForward}>
Właśnie też się nad tym zastanawiałam, bo zauważyłam, że lewy przycisk tak jakby się przycinał na samym początku zawsze - czyli trzeba było tak zrobić jednak. 😂 Dzięki za tipa - jutro ogarnę, jak będę mieć chwilę! ❤️

2021-03-31 00:13 UTC, anna130993 commented on src/components/features/Gallery/Gallery.module.scss
> +}
Z tym to w ogóle jest zabawnie, bo jak wejdziesz tylko w devTools i tyle, to faktycznie tak jest - ale jak przełączysz się na tryb RWD i tableta, to wtedy jest tak jak powinno z kolei. 😂

2021-03-31 00:44 UTC, szygadlinski commented on src/components/features/Gallery/Gallery.module.scss
> +}
Hm, no ja się przełączałem na tryb RWD i zmieniałem sobie szerokość wtedy 🤔

2021-03-31 00:58 UTC, anna130993 commented on src/components/features/Gallery/Gallery.module.scss
> +}
Huh, ja wchodziłam w RWD i przełączałam z kolei na górnym pasku pomiędzy tabletem, mobile L i mobile M. 🤔 No nic, jutro postaram się przy okazji wcześniejszego tipa zrobić dochodzenie - się ogarnie. 😂❤ #incepcja

2021-03-31 18:26 UTC, anna130993 commented
Okej, sprawa ma się tak - przeniosłam wszystkie rzeczy związane z eventami do onClicka (chociażby po to, żeby było jednolicie z innymi komponentami - plus, tbh, wolę taką wersję), aczkolwiek nie wiem, na ile to ma w gruncie rzeczy wpływ na to, co dzieje się ze sliderem. Zauważyłam, że nawet jeszcze przed zmianami nigdy nie było problemu z prawym przyciskiem/forward - problem zawsze, ale to ZAWSZE jest z lewej strony i nie zdziwiłabym się, gdyby krył się za tym jakiś bug, którego ja w tej chwili dokładnie nie widzę. 🤷‍♀️ Próbowałam bawić się trochę odpowiednią funkcją, bo akurat miałam chwilę, ale żadna inna konfiguracja, którą gdzieś tam dobrałam na podstawie forward nie działała tak dobrze jak oryginalna - która jak już zadziała, działa jak złoto. 
Testowałam wszystko z poziomu UX i sam slider czasami działa gładko od razu, a czasami "krztusi się" i dopiero po "pchnięciu" (np. kliknięciu dwa razy pod sliderem) rusza i tak już zostaje bez późniejszych zacięć.

Jeśli chodzi o samą widoczność, to jak Boga kocham, u mnie od 768px w dół wyświetla się idealnie tak, jak powinno być, czy to skaczę po górnym pasku, czy zmniejszam szerokość draggingiem - mogę nawet screenshoty zrobić. 😂

2021-03-31 21:06 UTC, doforever reviewed
Dla mnie przeróbka onClicków na minus, ale pewnie dlatego, że ja to pisałam ;-)

2021-03-31 21:06 UTC, doforever commented on src/components/features/Gallery/Gallery.js
> +                        `${handleSliderBackward(event)} ${event.preventDefault()}`
Mam pytanie do tej zmiany. Czemu zmieniłaś funkcję handleSliderBackward a potem doklejasz w kodzie event.preventDefault? Dla mnie czytelność tego rozwiązania jest dużo słabsza.

2021-03-31 21:06 UTC, doforever commented on src/components/features/Gallery/Gallery.js
> +                      }
tu to samo pytanie

2021-03-31 21:10 UTC, anna130993 commented on src/components/features/Gallery/Gallery.js
> +                        `${handleSliderBackward(event)} ${event.preventDefault()}`
No właśnie wpadła mi do głowy po drodze jeszcze jedna rzecz i zaraz będę ją jeszcze wypróbowywać, także tu się jeszcze może zmienić. :)

2021-03-31 22:16 UTC, anna130993 commented
Okej, koniec końców sprawa ma się tak - próbowałam różnych pomysłów, musiałam się od nich odrywać, bo życie, znowu wracałam, nic nie działało idealnie - aż zajrzałam znowu tutaj, i zainspirowana pojawieniem się @doforever postanowiłam po kolejnym niewypale wrócić do basics i... wszystko działa idealnie. Slider działa jak marzenie z poziomu UX (testowałam kilka razy) i tbh, nie mam pojęcia, dlaczego wcześniej lewy przycisk się przycinał. 🤷‍♀️ Na wszelki wypadek nie usuwałam commitów, a dodałam plik jeszcze raz (wracając do basics, przeklejałam je z mastera - może wcześniej przy niezbędnych modyfikacjach niechcący usunęłam coś drobnego i mi umknęło? Wolę nie ryzykować 😀 ). 

Moral of the story - czasami musimy nabrać perspektywy, żeby w pełni docenić punkt startowy. Albo sprawdzić, czy niczego nie naruszyliśmy w punkcie startowym. (Druga opcja prawdopodobnie byłaby lepsza, jeżeli chodzi o czas i pracę, let's face it 😂). 

Jeżeli chodzi o widoczność, to u mnie przy 768px i poniżej wyświetla się wszystko idealnie tak, jak powinno - bez względu na to, czy zmieniam szerokość na pasku, czy draggingiem - mogę nawet zrobić screenshoty. 😂

2021-03-31 23:24 UTC, szygadlinski commented
Hm, no to dziwne, ale u mnie wciąż jest jak było :P na tabletowych szerokościach obrazek pod sliderem, i `event` do wyrzucenia xD 

Screeny ode mnie:

![image](https://user-images.githubusercontent.com/73799676/113223134-cbf57200-9288-11eb-9c6a-e152096db48c.png)

![image](https://user-images.githubusercontent.com/73799676/113223151-d3b51680-9288-11eb-8fd6-14ca966ae4cf.png)

2021-03-31 23:41 UTC, anna130993 commented
Okej, Bogu dzięki za screeny, bo już wiem, że przynajmniej w jednej kwestii się po prostu nie dogadaliśmy - mi się wszystko pięknie wyświetla, bo ustawiłam max-width na 768px, czyli na PIONOWY tablet, a Ty go obróciłeś (o czym ja nie pomyślałam), masz 900px i już nie działa. 😂 Gimme a sec, już przestawiam. 😂

2021-03-31 23:57 UTC, anna130993 commented
Okej, już powinno wszystko hulać - nawet specjalnie zniszczyłam lokalnego brancha i ściągnęłam remote, żeby przetestować. 😂 Od niczego po spodem screen 😂 
![Screen -29](https://user-images.githubusercontent.com/73667449/113225321-a4ed6f00-928d-11eb-85a7-08dbae0a8360.JPG)

2021-04-01 00:00 UTC, anna130993 commented
W drugą stronę też działa. 😂 😂 😂 
![Screen -29](https://user-images.githubusercontent.com/73667449/113225497-13cac800-928e-11eb-9255-11ef8770f124.JPG)

2021-04-01 00:01 UTC, anna130993 commented
W drugą stronę u mnie też działa. 😂 😂 😂 
![Screen -29 2](https://user-images.githubusercontent.com/73667449/113225545-30670000-928e-11eb-9a1a-03dbc5fc0a09.JPG)

2021-04-01 20:11 UTC, merged