Wdp210301 68
odevpl/wdp-2103-01 pull request #77
Opened 2021-04-03 14:15 UTC by karolinaa178

TWoim zadaniem jest stworzenie nawigacji do podstron shop oraz product.

Klikając w menu obok wyszukiwarki jesteśmy przekierowanie na podstronę shop z id równym przyciskowi.
Np. klikając w przycisk Furniture zostajemy przeniesieni na podstronę /shop/furniture
Wyjątkiem jest przycisk Home, który kieruje na stronę główną.

Klikając na nazwę produktu w sekcji New Furniture zostajemy przeniesieni na podstronę product z id równym id produktu.
Np. klikając na produkt Aenean Ru Bristique 1 zostajemy przeniesieni na podstronę /product/aenean_ru_bristique_1.
Mam nadzieję, że nic nie przekombinowałam i wszystko działa :)

2021-04-05 15:28 UTC, doforever requested changes

2021-04-05 15:28 UTC, doforever commented on src/components/layout/MenuBar/MenuBar.js
> +                </li>
Tu też łatwiejsze do ogarnięcia byłyby linki niż lub navlinki z react-router-dom

2021-04-05 15:28 UTC, doforever commented on src/components/views/ProductList/ProductList.js
> +                              <ProductBox {...item} match={match} />
Nie widzę w ProductBox propsa match

2021-04-05 15:28 UTC, doforever commented on src/components/views/ProductPage/ProductPageContainer.js
> +    products: getAll(state),
Pobierasz właściwy product ze stora, a do czego potrzebne są wszystkie produkty? Do czego jest props image? Czy nie ma go w produkcie?

2021-04-05 15:28 UTC, doforever commented on src/components/views/ProductPage/ProductPage.js
> +  }, [currentProduct, products]);
W kontenerze masz pobrany właściwy produkt według id. Dlaczego tu znowu filtrujesz wszystkie produkty?

2021-04-05 15:28 UTC, doforever commented on src/components/views/ProductPage/ProductPage.js
> +                      <p className={styles.activeImage}>{activeImage}</p>
w tej linii zmienna activeImage renderuje się jako 0 i wyświetla się na powierzchni osadzonego obrazka

2021-04-05 15:32 UTC, doforever requested changes
Co do rozwiązania nawigacji mam kilka uwag, które mogłyby Ci ułatwić pracę na przyszłość, ale działa z tego co widzę dobrze. Niestety trochę pomieszało się w kodzie w czasie rebasa i kod się wysypuje.

2021-04-05 18:01 UTC, karolinaa178 commented on src/components/common/ProductBox/ProductBox.js
> +export default ProductBox;
Załuważyłam tą zmianę po czasie  i pewnie dlatego został przywrócony. Zapomniałam go usunąć, ale wprowadziłam swoje zmiany w odpowiednim ProductBox

2021-04-06 09:14 UTC, doforever approved these changes

2021-04-06 09:15 UTC, doforever commented
Kod wymaga lekkiego refactoringu, ale na tą chwilę działa wystarczająco dobrze.

2021-04-06 09:15 UTC, PatrykBula approved these changes

2021-04-06 09:15 UTC, merged